# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = 'ambry'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/wily64"

  config.vm.synced_folder "home-ambry/", "/home/vagrant/ambry"
  config.vm.synced_folder "var-ambry/", "/var/ambry"

  config.vm.network "private_network", type: "dhcp"

  config.vm.network "public_network", type: "dhcp"

  config.vm.provider "virtualbox" do |v|
    # Need more memory to get Pandas to complile
    v.memory = 2000
  end

  #config.vm.provision "shell", inline: $script
  config.vm.provision "shell", path: "../install/install-ubuntu.sh"

end
