#!/bin/sh
#
# use in ambry.wareouse.sqlite.load_remote() to load data into sqlite from a URL
#
url=$1
db_path=$2
table_name=$3

curl -s -L --compressed "$url" | sqlite3 -header -separator ',' $db_path ".import /dev/stdin $table_name"
