#!/bin/sh
#
# Build all buildable bundles in the source directory

# Copyright (c) 2013 Clarinova. This file is licensed under the terms of the
# Revised BSD License, included in this distribution as LICENSE.txt

while true; do
    ambry source buildable && ambry source buildable -Fvid | xambry build --clean --install

    if [ $? != 0 ]; then
        exit 0
    fi

done

