#!/bin/sh
#Management program interface for bundles. Equivalent to calling "python -mdatabundles
#in a bundle directory

# Copyright (c) 2013 Clarinova. This file is licensed under the terms of the
# Revised BSD License, included in this distribution as LICENSE.txt

exec python -mambry.cli "$@"