#!/bin/sh
#Management program interface for bundles. Equivalent to calling "ambry bundle -d `pwd` "
#in a bundle directory

# Copyright (c) 2015 Civic Knowledge. This file is licensed under the terms of the
# Revised BSD License, included in this distribution as LICENSE.txt

python -m ambry.cli bundle  $@