# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = 'ambry-dev'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "saucy64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box"


  config.vm.provider "virtualbox" do |v|
    # Need more memory to get Pandas to complile
    v.memory = 1500
  end


  config.vm.provision "shell", path: "../install-ubuntu.sh"
    
  # Re-install the config zs the vagrant user
  $script = <<SCRIPT
rm /etc/ambry.yaml
chown -R vagrant.vagrant /ambry
su vagrant ambry config install 
SCRIPT
    
  config.vm.provision "shell", inline: $script
    
end







